/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialLockerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lock"
      | "lockerPass"
      | "locks"
      | "nextLockId"
      | "registry"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LockCreated" | "LockWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "lock",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lockerPass",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "locks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextLockId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockerPass", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextLockId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace LockCreatedEvent {
  export type InputTuple = [
    lockId: BigNumberish,
    owner: AddressLike,
    token: AddressLike
  ];
  export type OutputTuple = [lockId: bigint, owner: string, token: string];
  export interface OutputObject {
    lockId: bigint;
    owner: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockWithdrawnEvent {
  export type InputTuple = [lockId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [lockId: bigint, owner: string];
  export interface OutputObject {
    lockId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialLocker extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialLocker;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialLockerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lock: TypedContractMethod<
    [
      _token: AddressLike,
      _encryptedAmount: BytesLike,
      _amountProof: BytesLike,
      _encryptedTime: BytesLike,
      _timeProof: BytesLike,
      _encryptedKPI: BytesLike,
      _kpiProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  lockerPass: TypedContractMethod<[], [string], "view">;

  locks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean] & {
        unlockTime: string;
        targetKPI: string;
        amount: string;
        token: string;
        withdrawn: boolean;
      }
    ],
    "view"
  >;

  nextLockId: TypedContractMethod<[], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [_lockId: BigNumberish, _currentKPI: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _encryptedAmount: BytesLike,
      _amountProof: BytesLike,
      _encryptedTime: BytesLike,
      _timeProof: BytesLike,
      _encryptedKPI: BytesLike,
      _kpiProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockerPass"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "locks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean] & {
        unlockTime: string;
        targetKPI: string;
        amount: string;
        token: string;
        withdrawn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextLockId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [_lockId: BigNumberish, _currentKPI: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LockCreated"
  ): TypedContractEvent<
    LockCreatedEvent.InputTuple,
    LockCreatedEvent.OutputTuple,
    LockCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LockWithdrawn"
  ): TypedContractEvent<
    LockWithdrawnEvent.InputTuple,
    LockWithdrawnEvent.OutputTuple,
    LockWithdrawnEvent.OutputObject
  >;

  filters: {
    "LockCreated(uint256,address,address)": TypedContractEvent<
      LockCreatedEvent.InputTuple,
      LockCreatedEvent.OutputTuple,
      LockCreatedEvent.OutputObject
    >;
    LockCreated: TypedContractEvent<
      LockCreatedEvent.InputTuple,
      LockCreatedEvent.OutputTuple,
      LockCreatedEvent.OutputObject
    >;

    "LockWithdrawn(uint256,address)": TypedContractEvent<
      LockWithdrawnEvent.InputTuple,
      LockWithdrawnEvent.OutputTuple,
      LockWithdrawnEvent.OutputObject
    >;
    LockWithdrawn: TypedContractEvent<
      LockWithdrawnEvent.InputTuple,
      LockWithdrawnEvent.OutputTuple,
      LockWithdrawnEvent.OutputObject
    >;
  };
}
