/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IComplianceRegistry,
  IComplianceRegistryInterface,
} from "../../contracts/IComplianceRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IComplianceRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IComplianceRegistryInterface {
    return new Interface(_abi) as IComplianceRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IComplianceRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IComplianceRegistry;
  }
}
